package com.timurradko.bot.shared.entity.security;

public enum Feature {
    //admins feature
    SHOW_USERS_FOR_ADMIN,
    EDIT_USER,
    ADD_QUESTION,
    VIEW_ALL_TEST_QUESTIONS,
    CHANGE_USER_LEVEL,
    CHANGE_USER_STATUS,
    EDIT_COURSE,
    ADMIN_CHANGE_COURSE,
    ADD_NEW_COURSE,
    ADD_INFO_ABOUT_COURSE,
    CHOOSE_COURSE_ACTION,
    DELETE_COURSE,
    READ_COURSE_DESCRIPTION,
    READ_COURSE_TITLE,
    SELECT_COURSE_TO_DELETE,
    CHANGE_PARAMETERS_COURSE,
    CHANGES_CHOOSE;
}
